### ISSUE TITLE
Simple error getting client ...

### ISSUE THREAD

**Issue by jamesladd** [mhuggins/a2z#11]
$ rails c
Loading development environment (Rails 4.1.1)
2.1.2 :001 > config = YAML.load_file(Rails.root.join('config', 'amazon.yml'))
 => {"key"=>"your_key", "secret"=>"your_secret", "tag"=>"your_tag"} 
2.1.2 :002 > client = A2z::Client.new(config)
NoMethodError: undefined method `key=' for #A2z::Client:0x00000004fd4068

Why is key= undefined? and yet your build is passing?

**Comment by mhuggins** [comment]
Can you verify that you're using v 0.1.3 of the gem?  There was an issue in previous versions where a2z was depending on _any version_ of the jeff gem, and it was updated without me knowing to no longer assign the key value in the same way.  The 0.1.3 update should have fixed that by specifying a specific version of the jeff gem.

**Comment by jamesladd** [comment]
Hey Matt, Due to my timeframes I went with another gem, will circle back
when I can and check on your again as it looks very complete & more useful

**Comment by mhuggins** [comment]
Cool, no worries.  I'm going to close this for now then, but please reopen if you try again and still have issues!
