### ISSUE TITLE
VCR interoperability

### ISSUE THREAD

**Issue by squarism** [mhuggins/a2z#3]
I couldn't get this to work with VCR.  Just thought I'd post on what happened.

a2z requires Jeff.  jeff-0.5.0 depends on [excon (~> 0.18.0)]

If I wire up VCR with excon then it complains:
`You are using Excon 0.18.5. VCR is known to work with Excon >= 0.9.6, < 0.17.
It may not work with this version.`

So there's an impasse here.  I have to have 0.18.0+ but I can't have 0.18.0+ :speak_no_evil: 

Does a2z really need >= 0.18.0?

I understand that this is really an issue with VCR but I thought I'd ask how you'd cache or mock the webservice calls to AWS.  Thx mucho.

Weirdly, VCR managed to write something out as I was testing different versions.  I got a YAML file with a User-Agent of Jeff and `recorded_with: VCR 2.0.0.rc2`.  So maybe there's a path forward there.  I'll play with it some more.

**Comment by mhuggins** [comment]
It sounds like this is an issue that should be opened with [jeff](https://github.com/papercavalier/jeff) since that's the gem requiring [excon](https://github.com/geemus/excon).  I would check with the owner of jeff to see if excon ~> 0.18.0 is really needed.

**Comment by mhuggins** [comment]
Actually, now that I look into it a bit further, it looks like you must be using jeff 0.5.0, which includes [this commit](https://github.com/papercavalier/jeff/commit/9a27cef13837f54588aa82c8c1058dc5ba9a2c32).  If you just use an earlier version of jeff, (which a2z allows), then you should be fine.

Feel free to reopen if you need more help with this.

**Comment by squarism** [comment]
Sorry for the delay.  Thanks much for the answer.  Yes I rolled back to jeff 0.4.3 and I'm able to cache requests using a2z (through jeff -> excon) like you said.  This is my relevant parts of my Gemfile:

```
# in main part of gemfile, not in dev or test groups
gem "a2z", "~> 0.1.1"
gem 'jeff', "~> 0.4.3"
```

I'm super happy about this because I can iterate really fast using vcr + zeus without burning through my amazon quota and getting 503's.

**Comment by mhuggins** [comment]
VCR FTW :smile:
