### ISSUE TITLE
No offers available for responses?

### ISSUE THREAD

**Issue by xapss** [mhuggins/a2z#5]
Hi there. First of all: awesome gem. Seriously nice, extremely nice compared to vacuum/sucker.

I've been successfully getting responses, but i'm having trouble with offers.

Somehow I cant get any offer across. Is there something I forgot?

```
client = A2z::Client.new(key: '[key]', secret: '[secret]', tag: '[tag]')

response = client.item_lookup do
  id 'B004MPQXZ0' (tried several products, also the ones that were for sale online)
end

response.item.offers = always nil. Any ideas why?
```

Thanks again!

**Comment by mhuggins** [comment]
From the readme:

> Offers are accessible on items when the "[Offers](http://docs.aws.amazon.com/AWSECommerceService/latest/DG/RG_Offers.html)", "[OfferListings](http://docs.aws.amazon.com/AWSECommerceService/latest/DG/RG_OfferListings.html)", or "[OfferFull](http://docs.aws.amazon.com/AWSECommerceService/latest/DG/RG_OfferFull.html)" response group is included as part of an item lookup or item search request.

Make sure you pass one of those values as the `response_group` when performing your item lookup, e.g.:

```
client = A2z::Client.new(key: '[key]', secret: '[secret]', tag: '[tag]')

response = client.item_lookup do
  id 'B004MPQXZ0'
  response_group 'Offers'
end
```

Note that you can also pass multiple values (as an array of strings, or as a comma-separated string) to `response_group` if you need more than just offers returned too.

Feel free to reopen this issue if you still run into issues after giving this a shot. :)
