### ISSUE TITLE
Exception received while fetching item from amazon

### ISSUE THREAD

**Issue by jchauhan** [mhuggins/a2z#7]
Exception details are below:

NoMethodError: undefined method `[]' for nil:NilClass
    from ~/.rvm/gems/ruby-1.9.3-p286/gems/a2z-0.1.1/lib/a2z/responses/offer_summary.rb:51:in`block in from_response'

```
      if data['LowestNewPrice']
        offer_summary.lowest_new_price = Money.new(data['LowestNewPrice']['Amount'].to_i, data['LowestNewPrice']['CurrencyCode'])
      end

      if data['LowestUsedPrice']
        offer_summary.lowest_used_price = Money.new(data['LowestNewPrice']['Amount'].to_i, data['LowestNewPrice']['CurrencyCode'])
      end
```

**Comment by mhuggins** [comment]
Can you paste the code you used to make the call?

**Comment by jchauhan** [comment]
The code to send a request to amazon is following:

  def self.send_search_req(q, cat, page = 1, per_page = 10, options = {})
    client = A2z::Client.new(@@config)
    response = client.item_search do
      category cat
      item_page page
      keywords q
      response_group 'Medium'
    end
    response
  end

After going through the a2z library it looks like it is typo bug. In the following lines of code (lib/a2z/responses/offer_summary.rb, line number 51), if you notice, data['LowestUsedPrice'] is checked for not being nil, however data['LowestNewPrice'] is used to to set value of offer_summary.lowest_used_price.

lib/a2z/responses/offer_summary.rb:51:inblock in from_response'
      if data['LowestNewPrice']
        offer_summary.lowest_new_price = Money.new(data['LowestNewPrice']['Amount'].to_i, data['LowestNewPrice']['CurrencyCode'])
      end

```
  if data['LowestUsedPrice']
    offer_summary.lowest_used_price = Money.new(data['LowestNewPrice']['Amount'].to_i, data['LowestNewPrice']['CurrencyCode'])
  end
```

**Comment by jchauhan** [comment]
Any Updated. We want to fix it before going live.

**Comment by mhuggins** [comment]
Just updated the gem to 0.1.2 with a fix.  Please let me know if you're still having any issues.  Thanks!

**Comment by jchauhan** [comment]
Many Thanks. It has fixed the issue.

**Comment by mhuggins** [comment]
:thumbsup:
